// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSSFJBkhc3IqKnFE5CrmA8VUnOR8OfTuo',
    appId: '1:15999642239:android:fe691c99f0cbb91621ad4a',
    messagingSenderId: '15999642239',
    projectId: 'si1700-chika',
    databaseURL: 'https://si1700-chika-default-rtdb.firebaseio.com',
    storageBucket: 'si1700-chika.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1XTNAGYUU4sIE-bwNUgeIVSubaIiX0I',
    appId: '1:15999642239:ios:306aec8b347fd27021ad4a',
    messagingSenderId: '15999642239',
    projectId: 'si1700-chika',
    databaseURL: 'https://si1700-chika-default-rtdb.firebaseio.com',
    storageBucket: 'si1700-chika.firebasestorage.app',
    iosBundleId: 'com.example.commanderCounter',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0eSPsjB1F7pzrYQzqf58Vju4pyHRluec',
    appId: '1:15999642239:web:319153272feadd1b21ad4a',
    messagingSenderId: '15999642239',
    projectId: 'si1700-chika',
    authDomain: 'si1700-chika.firebaseapp.com',
    databaseURL: 'https://si1700-chika-default-rtdb.firebaseio.com',
    storageBucket: 'si1700-chika.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg1XTNAGYUU4sIE-bwNUgeIVSubaIiX0I',
    appId: '1:15999642239:ios:306aec8b347fd27021ad4a',
    messagingSenderId: '15999642239',
    projectId: 'si1700-chika',
    databaseURL: 'https://si1700-chika-default-rtdb.firebaseio.com',
    storageBucket: 'si1700-chika.firebasestorage.app',
    iosBundleId: 'com.example.commanderCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0eSPsjB1F7pzrYQzqf58Vju4pyHRluec',
    appId: '1:15999642239:web:722a9e34601feb5521ad4a',
    messagingSenderId: '15999642239',
    projectId: 'si1700-chika',
    authDomain: 'si1700-chika.firebaseapp.com',
    databaseURL: 'https://si1700-chika-default-rtdb.firebaseio.com',
    storageBucket: 'si1700-chika.firebasestorage.app',
  );
}
